from __future__ import annotations

import enum
import uuid
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Optional

from sqlalchemy import DateTime, Enum, Float, ForeignKey, Index, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.db.models.post import ProcessedPost


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class MatchStatus(str, enum.Enum):
    PENDING = "pending"       # auto-generated, awaiting human/system review
    CONFIRMED = "confirmed"   # verified match (future: user confirms via app)
    REJECTED = "rejected"     # false positive (future: user rejects via app)


class Match(Base):
    """
    A candidate match between a 'lost' post and a 'found' post.

    Generated by the matching engine based on:
    - Rule-based scoring (item type, location, temporal proximity)
    - Embedding cosine similarity (Phase 2)

    match_reasons stores the breakdown for explainability:
    {
        "item_type_match": 0.40,
        "location_match": 0.35,
        "temporal_score": 0.15,
        "person_name_match": 0.10,
        "embedding_similarity": 0.87
    }
    """

    __tablename__ = "matches"

    # ── Primary key ─────────────────────────────────────────────────────────
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    # ── The matched pair ─────────────────────────────────────────────────────
    lost_post_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("processed_posts.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    found_post_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("processed_posts.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ── Scoring ──────────────────────────────────────────────────────────────
    match_score: Mapped[float] = mapped_column(
        Float, nullable=False,
        comment="Overall match score [0, 1] — higher = more confident"
    )
    match_reasons: Mapped[Optional[dict]] = mapped_column(
        JSONB, nullable=True,
        comment="Score breakdown per signal — for explainability"
    )

    # ── Status ───────────────────────────────────────────────────────────────
    status: Mapped[MatchStatus] = mapped_column(
        Enum(MatchStatus, name="match_status_enum"),
        nullable=False,
        default=MatchStatus.PENDING,
        server_default="pending",
        index=True,
    )

    # ── Audit ────────────────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        default=_utcnow, server_default=func.now()
    )

    # ── Relationships ────────────────────────────────────────────────────────
    lost_post: Mapped["ProcessedPost"] = relationship(
        "ProcessedPost",
        foreign_keys=[lost_post_id],
        back_populates="lost_matches",
        lazy="raise",
    )
    found_post: Mapped["ProcessedPost"] = relationship(
        "ProcessedPost",
        foreign_keys=[found_post_id],
        back_populates="found_matches",
        lazy="raise",
    )

    # ── Indices ──────────────────────────────────────────────────────────────
    __table_args__ = (
        # Prevent duplicate (lost, found) pairs
        Index("uq_matches_pair", "lost_post_id", "found_post_id", unique=True),
        # Fast lookup of pending matches for review
        Index("ix_matches_pending", "status",
              postgresql_where="status = 'pending'"),
    )

    def __repr__(self) -> str:
        return (
            f"<Match id={self.id} score={self.match_score:.2f} "
            f"status={self.status}>"
        )
