"""initial_schema

Revision ID: 57f2fb98f457
Revises: 
Create Date: 2026-04-11 00:16:03.908793

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '57f2fb98f457'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facebook_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.String(length=64), nullable=False, comment='Native Facebook group / page ID'),
    sa.Column('group_url', sa.Text(), nullable=False, comment='Full canonical URL of the group'),
    sa.Column('group_name', sa.String(length=256), nullable=False, comment='Human-readable display name'),
    sa.Column('scrape_enabled', sa.Boolean(), server_default='true', nullable=False, comment='Toggle scraping without deleting the record'),
    sa.Column('scrape_priority', sa.Integer(), nullable=False, comment='1=high, 2=medium, 3=low'),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True, comment='Wall-clock time the last scrape job started for this group'),
    sa.Column('last_post_timestamp', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the most recent post successfully ingested. Next run fetches posts after (this - overlap_hours).'),
    sa.Column('cursor_token', sa.Text(), nullable=True, comment='Apify/BrightData pagination token from the last run'),
    sa.Column('post_count', sa.Integer(), server_default='0', nullable=False, comment='Running total of posts ingested from this group'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facebook_groups'))
    )
    op.create_index(op.f('ix_facebook_groups_group_id'), 'facebook_groups', ['group_id'], unique=True)
    op.create_table('scrape_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('APIFY', 'BRIGHTDATA', name='scraper_provider_enum'), nullable=False),
    sa.Column('scraper_version', sa.String(length=64), nullable=True, comment='Apify actor version or BrightData scraper version'),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'DONE', 'FAILED', 'SKIPPED', name='job_status_enum'), server_default='QUEUED', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('posts_scraped', sa.Integer(), server_default='0', nullable=False, comment='Number of posts returned by the scraper (before dedup)'),
    sa.Column('posts_new', sa.Integer(), server_default='0', nullable=False, comment='Net-new posts inserted (after dedup)'),
    sa.Column('cost_usd', sa.Float(), nullable=True, comment='Reported cost in USD from provider — for budget monitoring'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Last error message — set when status=failed'),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['facebook_groups.id'], name=op.f('fk_scrape_jobs_group_id_facebook_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrape_jobs'))
    )
    op.create_index(op.f('ix_scrape_jobs_group_id'), 'scrape_jobs', ['group_id'], unique=False)
    op.create_index(op.f('ix_scrape_jobs_status'), 'scrape_jobs', ['status'], unique=False)
    op.create_table('raw_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.String(length=64), nullable=False, comment='Native Facebook post ID — primary dedup key'),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('scrape_job_id', sa.UUID(), nullable=True, comment='Which job produced this post — for debugging / cost attribution'),
    sa.Column('text', sa.Text(), nullable=True, comment='Raw post body — may be Arabic, MSA, or dialect'),
    sa.Column('post_text_checksum', sa.String(length=64), nullable=True, comment='SHA-256 of cleaned text — detect if post was edited on re-scrape'),
    sa.Column('author_name', sa.String(length=256), nullable=True),
    sa.Column('author_id', sa.String(length=64), nullable=True, comment='Facebook user ID — more stable identifier than name'),
    sa.Column('author_profile_url', sa.Text(), nullable=True),
    sa.Column('post_url', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True, comment='Original post timestamp from Facebook'),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When our scraper captured this post'),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of image URLs: [{url, width, height}]'),
    sa.Column('engagement', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='{likes: int, comments: int, shares: int}'),
    sa.Column('comments_sample', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Top 3 comments — often contain contact info missed in post body'),
    sa.Column('scraper_version', sa.String(length=64), nullable=True, comment='Apify actor version / BrightData scraper version used'),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full original scraper response — for reprocessing or debugging'),
    sa.Column('is_processed', sa.Boolean(), server_default='false', nullable=False, comment='False = waiting in processing queue'),
    sa.Column('processing_attempts', sa.Integer(), server_default='0', nullable=False, comment='Number of DSPy processing attempts — stops at max_retries'),
    sa.Column('processing_error', sa.Text(), nullable=True, comment='Last error message if processing failed'),
    sa.ForeignKeyConstraint(['group_id'], ['facebook_groups.id'], name=op.f('fk_raw_posts_group_id_facebook_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], name=op.f('fk_raw_posts_scrape_job_id_scrape_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_posts'))
    )
    op.create_index(op.f('ix_raw_posts_group_id'), 'raw_posts', ['group_id'], unique=False)
    op.create_index(op.f('ix_raw_posts_post_id'), 'raw_posts', ['post_id'], unique=True)
    op.create_index('ix_raw_posts_posted_at', 'raw_posts', ['posted_at'], unique=False)
    op.create_index('ix_raw_posts_unprocessed', 'raw_posts', ['is_processed', 'processing_attempts'], unique=False, postgresql_where='is_processed = false')
    op.create_table('processed_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_post_id', sa.UUID(), nullable=False),
    sa.Column('post_type', sa.Enum('LOST', 'FOUND', 'IRRELEVANT', name='post_type_enum'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True, comment='DSPy confidence score [0, 1]'),
    sa.Column('item_type', sa.String(length=256), nullable=True, comment="Type of item/person — e.g. 'wallet', 'child', 'dog'"),
    sa.Column('person_name', sa.String(length=256), nullable=True, comment='Name of person mentioned in the post'),
    sa.Column('location_raw', sa.Text(), nullable=True, comment='Location string exactly as extracted from text'),
    sa.Column('location_normalized', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='{city, area, country, coords: {lat, lng}}'),
    sa.Column('contact_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='{phone, whatsapp, facebook_profile, other}'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True, comment='Gemini text-embedding-004 vector (768-dim) for similarity search'),
    sa.Column('model_version', sa.String(length=64), nullable=True, comment='DSPy + Gemini model identifier used for this extraction'),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_post_id'], ['raw_posts.id'], name=op.f('fk_processed_posts_raw_post_id_raw_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processed_posts'))
    )
    op.create_index(op.f('ix_processed_posts_post_type'), 'processed_posts', ['post_type'], unique=False)
    op.create_index(op.f('ix_processed_posts_raw_post_id'), 'processed_posts', ['raw_post_id'], unique=True)
    op.create_index('ix_processed_posts_type_item', 'processed_posts', ['post_type', 'item_type'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lost_post_id', sa.UUID(), nullable=False),
    sa.Column('found_post_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False, comment='Overall match score [0, 1] — higher = more confident'),
    sa.Column('match_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Score breakdown per signal — for explainability'),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', name='match_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['found_post_id'], ['processed_posts.id'], name=op.f('fk_matches_found_post_id_processed_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lost_post_id'], ['processed_posts.id'], name=op.f('fk_matches_lost_post_id_processed_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    op.create_index(op.f('ix_matches_found_post_id'), 'matches', ['found_post_id'], unique=False)
    op.create_index(op.f('ix_matches_lost_post_id'), 'matches', ['lost_post_id'], unique=False)
    op.create_index('ix_matches_pending', 'matches', ['status'], unique=False, postgresql_where="status = 'PENDING'")
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_index('uq_matches_pair', 'matches', ['lost_post_id', 'found_post_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_matches_pair', table_name='matches')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index('ix_matches_pending', table_name='matches', postgresql_where="status = 'PENDING'")
    op.drop_index(op.f('ix_matches_lost_post_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_found_post_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index('ix_processed_posts_type_item', table_name='processed_posts')
    op.drop_index(op.f('ix_processed_posts_raw_post_id'), table_name='processed_posts')
    op.drop_index(op.f('ix_processed_posts_post_type'), table_name='processed_posts')
    op.drop_table('processed_posts')
    op.drop_index('ix_raw_posts_unprocessed', table_name='raw_posts', postgresql_where='is_processed = false')
    op.drop_index('ix_raw_posts_posted_at', table_name='raw_posts')
    op.drop_index(op.f('ix_raw_posts_post_id'), table_name='raw_posts')
    op.drop_index(op.f('ix_raw_posts_group_id'), table_name='raw_posts')
    op.drop_table('raw_posts')
    op.drop_index(op.f('ix_scrape_jobs_status'), table_name='scrape_jobs')
    op.drop_index(op.f('ix_scrape_jobs_group_id'), table_name='scrape_jobs')
    op.drop_table('scrape_jobs')
    op.drop_index(op.f('ix_facebook_groups_group_id'), table_name='facebook_groups')
    op.drop_table('facebook_groups')
    # ### end Alembic commands ###
