"""add sent_to_dotnet to processed_posts

Revision ID: 0201ff98d6b8
Revises: 2579bf2b70ce
Create Date: 2026-05-10 01:44:16.068336

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0201ff98d6b8'
down_revision: Union[str, None] = '2579bf2b70ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_posts', sa.Column('sent_to_dotnet', sa.Boolean(), server_default='false', nullable=False, comment='True if this post was successfully sent to the .NET backend'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_posts', 'sent_to_dotnet')
    # ### end Alembic commands ###
