"""simplify

Revision ID: 2579bf2b70ce
Revises: 57f2fb98f457
Create Date: 2026-05-04 03:44:46.330003

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2579bf2b70ce'
down_revision: Union[str, None] = '57f2fb98f457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_found_post_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_lost_post_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_pending'), table_name='matches', postgresql_where="(status = 'PENDING'::match_status_enum)")
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('uq_matches_pair'), table_name='matches')
    op.drop_table('matches')
    op.drop_column('processed_posts', 'embedding')
    op.drop_column('processed_posts', 'model_version')
    op.drop_column('processed_posts', 'confidence_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_posts', sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='DSPy confidence score [0, 1]'))
    op.add_column('processed_posts', sa.Column('model_version', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='DSPy + Gemini model identifier used for this extraction'))
    op.add_column('processed_posts', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True, comment='Gemini text-embedding-004 vector (768-dim) for similarity search'))
    op.create_table('matches',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lost_post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('found_post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Overall match score [0, 1] — higher = more confident'),
    sa.Column('match_reasons', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Score breakdown per signal — for explainability'),
    sa.Column('status', postgresql.ENUM('PENDING', 'CONFIRMED', 'REJECTED', name='match_status_enum'), server_default=sa.text("'PENDING'::match_status_enum"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['found_post_id'], ['processed_posts.id'], name=op.f('fk_matches_found_post_id_processed_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lost_post_id'], ['processed_posts.id'], name=op.f('fk_matches_lost_post_id_processed_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    op.create_index(op.f('uq_matches_pair'), 'matches', ['lost_post_id', 'found_post_id'], unique=True)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_index(op.f('ix_matches_pending'), 'matches', ['status'], unique=False, postgresql_where="(status = 'PENDING'::match_status_enum)")
    op.create_index(op.f('ix_matches_lost_post_id'), 'matches', ['lost_post_id'], unique=False)
    op.create_index(op.f('ix_matches_found_post_id'), 'matches', ['found_post_id'], unique=False)
    # ### end Alembic commands ###
